# Generated by Django 4.1.6 on 2023-02-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="role",
        ),
        migrations.AddField(
            model_name="member",
            name="Role",
            field=models.CharField(
                choices=[
                    ("1", "Admin - Can delete members"),
                    ("2", "General - Cannot delete members"),
                ],
                default="1",
                max_length=100,
            ),
        ),
    ]
