# Generated by Django 4.1.6 on 2023-02-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teamapp", "0003_alter_member_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="Role",
            new_name="role",
        ),
    ]
