# Generated by Django 4.1.6 on 2023-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamapp", "0004_rename_role_member_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("General", "General")],
                default="Admin",
                max_length=100,
            ),
        ),
    ]
